# Generated by Django 2.2.1 on 2019-05-25 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190525_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': (('superadmin', 'Super Admin'),)},
        ),
    ]
